### ISSUE TITLE
skimage version error?

### ISSUE THREAD

**Issue by markjessell** [cgre-aachen/gempy#244]
**Describe the bug**
geo_model.set_topography causes an error (probably related to the skimage version?)

~/anaconda3/envs/m2le/lib/python3.8/site-packages/map2loop-0.0.50-py3.8.egg/map2loop/m2l_export.py in loop2gempy(test_data_name, tmp_path, vtk_pth, orientations_file, contacts_file, groups_file, dtm_reproj_file, bbox, model_base, model_top, vtk)
    565     fp = dtm_reproj_file
    566     #print(fp)
--> 567     geo_model.set_topography(source='gdal',filepath=fp)
    568 
    569 

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/plot/decorators.py in pst(*args, **kwargs)
     99     def pst(*args, **kwargs):
    100         plot_object = kwargs.pop('plot_object') if 'plot_object' in kwargs else None
--> 101         topography = func(*args, **kwargs)
    102 
    103         if plot_object is not None:

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/model.py in set_topography(self, source, **kwargs)
    191         """
    192 
--> 193         self.grid.set_topography(source, **kwargs)
    194         self.update_from_grid()
    195         print(f'Active grids: {self.grid.grid_types[self.grid.active_grids]}')

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/data.py in set_topography(self, source, **kwargs)
    147             filepath = kwargs.get('filepath', None)
    148             if filepath is not None:
--> 149                 self.topography.load_from_gdal(filepath)
    150             else:
    151                 print('to load a raster file, a path to the file must be provided')

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/grid_modules/grid_types.py in load_from_gdal(self, filepath)
    374         self.topo = Load_DEM_GDAL(filepath, self.regular_grid)
    375         self._create_init()
--> 376         self._fit2model()
    377         self.type = 'real'
    378 

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/grid_modules/grid_types.py in _fit2model(self)
    408 
    409         if np.any(self.regular_grid.resolution[:2] - self.resolution) != 0:
--> 410             self._resize()
    411         else:
    412             self.values_3D_res = self.values_3D

~/anaconda3/envs/m2le/lib/python3.8/site-packages/gempy/core/grid_modules/grid_types.py in _resize(self)
    418 
    419     def _resize(self):
--> 420         self.values_3D_res = skimage.transform.resize(self.values_3D,
    421                                                       (self.regular_grid.resolution[0], self.regular_grid.resolution[1]),
    422                                                       mode='constant',

AttributeError: module 'skimage' has no attribute 'transform'

**Comment by pytzcarraldo** [comment]
This looks very odd 🤔 skimage definitely has a transfrom module in the current master branch: https://github.com/scikit-image/scikit-image/tree/master/skimage/transform 

Which version of skimage are you using? 


Although your specific error should have nothing to do with the functionality Miguel added to skimage, we are still waiting for his pull request to be accepted into skimage - but that should have nothing to do with this specific error. You could try installing the fork from @Leguark anyways by `pip install git+https://github.com/Leguark/scikit-image.git` - which should definitely work.

**Comment by elimh** [comment]
Hi! This used to be a bug, but it was fixed end of last year (fourth of november). Have you updated gempy since then? If not, updating should fix the problem.

**Comment by markjessell** [comment]
@pytzcarraldo I am using scikit-image 0.16.2 (I think the readme/dependencies has a typo as it talks about  1.14.2? I didn't know about the fork, so I'll try that and let you. 

@elimh I am running gempy 2.0.1

**Comment by markjessell** [comment]
Unfortunately, running the forked skimage 0.17.dev0 and gempy 2.0.1 I still get that error

**Comment by Leguark** [comment]
Hi Mark, sorry for coming late to the party. I think @elimh meant the gempy version. Sadly the pip version 2.0.1 is very old. You can try to install gempy from master should make the trick: 

pip install git+https://github.com/cgre-aachen/gempy.git 

Right now I am preparing the release of gempy 2.1 and hopefully from there on we will be more careful leaving a branch for hotfixes

**Comment by markjessell** [comment]
Hi Miguel

thanks that fixed the immediate problem, although now it crashes (memory crash so no error messages) at the gp.compute_model() stage but before I put in an issue I'll have to check the gempy input files to make sure they are the same as under windows.

cheers

Mark

**Comment by xuhenry** [comment]
Hello, everyone.
   I still have some errors as follows. The OS is Win10. 
Thanks a lot!

**Comment by xuhenry** [comment]
![1](https://user-images.githubusercontent.com/20606262/73623680-cbf3e500-4678-11ea-9853-68f3549aafdf.JPG)

**Comment by pytzcarraldo** [comment]
Hey @xuhenry 

It looks like the error you posted in #243 - if so could you tell us there if you tried the fix I've posted (downgrading pandas)?

**Comment by xuhenry** [comment]
Dear @pytzcarraldo.
Thanks for your help. But it still has the same errors.
Now I'm using Win10.
Thanks a lot!
Best regards,
Henry
