### ISSUE TITLE
Confusing mixed release states, pypi vs the release tags vs setup.py

### ISSUE THREAD

**Issue by AndrewAnnex** [cgre-aachen/gempy#436]
So I am seeing that gempy 2.2.1 is released on pypi, but the setup.py currently on master has a bad download url that points to "2.1.1tar.gz", and there is no 2.2.1 version tag yet on the repository.  missing release tags should be pushed to this repo to help fix things.

**Comment by AndrewAnnex** [comment]
I would like to bump this issue, 2.2.4 and 2.2.5 have been pushed to pypi recently but I don't see those releases on this repository or even in the setup.py file on the main branch???

**Comment by AlexanderJuestel** [comment]
This should be finally fixed in a patch, targeted with #640

**Comment by AndrewAnnex** [comment]
@AlexanderJuestel and @Leguark The core of this issue is still not addressed so this issue should not have been closed. There are a number of gempy releases on PyPI that have no corresponding git tag in this repository, this makes it extremely difficult to compare the version controlled source to what is distributed on PyPI. If no tagged git branches were made for these releases and it is impossible to recover the state of the repository at the time those versions were uploaded to PyPI, that is a understandable reason to close the issue, although some effort should be made to prevent such occurrences again (such as using github actions to push tagged releases to pypi instead)
